from core.environment import EnvConfig

def build_env_config(
    seed: int | None = None,
    fading_model: str = "rician",
    rician_k: float = 5.0,
    control_mode: str = "velocity",
    role_switching: bool = False,
    user_mobile: bool = False,
    use_los_model: bool = False,
    observation_mode: str = "full",
    normalize_observations: bool = True,
    enable_ntn: bool = False,
    satellite_altitude_km: float = 500.0,
    satellite_horizontal_offset_km: float = 100.0,
    ntn_carrier_frequency_hz: float = 2e9,
    ntn_atmospheric_loss_db: float = 0.5,
    ntn_rician_k_db: float = 10.0,
    # Multi-Eve (HPPP) params
    use_multiple_eves: bool = True,
    eve_density_lambda: float = 2e-5,
    eve_uncertainty_radius: float = 15.0,
) -> EnvConfig:
    return EnvConfig(
        seed=seed,
        fading_model=fading_model,
        rician_k=rician_k,
        control_mode=control_mode,
        role_switching=role_switching,
        user_mobile=user_mobile,
        use_los_model=use_los_model,
        observation_mode=observation_mode,
        normalize_observations=normalize_observations,
        enable_ntn=enable_ntn,
        satellite_altitude_km=satellite_altitude_km,
        satellite_horizontal_offset_km=satellite_horizontal_offset_km,
        ntn_carrier_frequency_hz=ntn_carrier_frequency_hz,
        ntn_atmospheric_loss_db=ntn_atmospheric_loss_db,
        ntn_rician_k_db=ntn_rician_k_db,
        use_multiple_eves=use_multiple_eves,
        eve_density_lambda=eve_density_lambda,
        eve_uncertainty_radius=eve_uncertainty_radius,
    )
